service: reto-softtek

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 10
  memorySize: 128
  architecture: arm64
  apiGateway:
    minimumCompressionSize: 1024

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - { 'Fn::GetAtt': ['FusionTable', 'Arn'] }
        - { 'Fn::GetAtt': ['CustomTable', 'Arn'] }

resources:
  Resources:
    FusionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FusionTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CustomTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CustomTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  api:
    handler: src/lambda.handler
    timeout: 10
    memorySize: 128
    events:
      - httpApi:
          method: any
          path: /{proxy+}
